export const BRAND_LOGOS: { name: string; src: string; scale?: number }[] = [
	// --- Named logos ---
	{ name: "Al Basrah Mas", src: "/logos/al-basrah-mas.webp", scale: 1.5 },
	{ name: "Al Aliaa", src: "/logos/al-aliaa.webp", scale: 1.2 },
	{ name: "Alshaba", src: "/logos/alshaba.webp", scale: 1.0 },
	{ name: "BGT", src: "/logos/basra-gate-terminal.webp", scale: 1.0 },
	{ name: "BOC", src: "/logos/basra-oil-company.webp", scale: 1.0 },
	{ name: "Basrah Gas", src: "/logos/basrah-gas.webp", scale: 1.0 },
	{ name: "BoB", src: "/logos/bank-of-baghdad.webp", scale: 1.0 },
	{ name: "Daewoo", src: "/logos/daewoo-engineering.webp", scale: 1.0 },
	{ name: "Dev Road", src: "/logos/development-road.webp", scale: 1.0 },
	{ name: "Earthlink", src: "/logos/earthlink.webp", scale: 1.0 },
	{ name: "Euler", src: "/logos/euler-hermes.webp", scale: 1.0 },
	{ name: "GFP", src: "/logos/great-fao-port.webp", scale: 1.0 },
	{ name: "ICC", src: "/logos/industrial-cities-corporation.webp", scale: 1.0 },
	{ name: "IDB", src: "/logos/international-development-bank.webp", scale: 1.0 },
	{ name: "IFPMC", src: "/logos/iraq-policy-making-forum.webp", scale: 1.0 },
	{ name: "Jwar Al Khaleej", src: "/logos/jwar-al-khaleej.webp", scale: 1.0 },
	{ name: "SOMO", src: "/logos/somo.webp", scale: 1.0 },
	{ name: "Nokia", src: "/logos/nokia.webp", scale: 1.0 },
	{ name: "Oliver Wyman", src: "/logos/oliver-wyman.webp", scale: 1.0 },
	{ name: "Iraqi Ports", src: "/logos/general-company-ports-iraq.webp", scale: 1.0 },
	{ name: "SuperCell", src: "/logos/supercell.webp", scale: 1.0 },
	{ name: "Technital", src: "/logos/technital.webp", scale: 1.0 },
	{ name: "Tiryaki Agro", src: "/logos/tiryaki-agro.webp", scale: 1.0 },
	{ name: "Visa", src: "/logos/visa.webp", scale: 1.0 },
	{ name: "Genesys", src: "/logos/genesys.webp", scale: 1.0 },
	{ name: "Imathia", src: "/logos/imathia-construction.webp", scale: 1.0 },
	{ name: "JIB", src: "/logos/jib.webp", scale: 1.0 },
	{ name: "Ministry of Transport", src: "/logos/ministry-of-transport.webp", scale: 1.0 },
	{ name: "Iraq Development Fund", src: "/logos/iraq-development-fund.webp", scale: 1.0 },
	{ name: "Kul Al Manafeth", src: "/logos/kul-al-manafeth.webp", scale: 1.0 },
	{ name: "Ministry of Oil", src: "/logos/ministry-of-oil.webp", scale: 1.0 },

	// --- Additional logos from public/logos ---
	{ name: "2", src: "/logos/asiacell.webp", scale: 1.0 },
	{ name: "4", src: "/logos/first-iraqi-bank.webp", scale: 1.0 },
	{ name: "4k logo", src: "/logos/techo-center-engineering.webp", scale: 1.0 },
	{ name: "6", src: "/logos/6.webp", scale: 1.0 },
	{ name: "9438 General Secretariat", src: "/logos/9438-general-secretariat.webp", scale: 1.0 },
	{ name: "Technital CMYK", src: "/logos/technital-cmyk.webp", scale: 1.0 },
	{ name: "Rida", src: "/logos/rida.webp", scale: 1.0 },
	{ name: "Ts", src: "/logos/tsingshan.webp", scale: 1.0 },
	{ name: "Logo 2", src: "/logos/logo-2.webp", scale: 1.0 },
	{ name: "NB Telecom", src: "/logos/nbtel.webp", scale: 1.0 },
	{ name: "Mufarrag x4", src: "/logos/iraq-24.webp", scale: 1.0 },

	// --- Picture logos ---
	{ name: "Picture 7", src: "/logos/toyota.webp", scale: 1.0 },
	{ name: "Picture 9", src: "/logos/picture9.webp", scale: 1.0 },
	{ name: "Picture 12", src: "/logos/picture12.webp", scale: 1.0 },
	{ name: "Picture 17", src: "/logos/fastlink.webp", scale: 1.0 },
	{ name: "Picture 18", src: "/logos/trade-bank-iraq.webp", scale: 1.0 },
	{ name: "Picture 182", src: "/logos/first-iraqi-islamic-bank.webp", scale: 1.0 },
	{ name: "Picture 19", src: "/logos/picture19.webp", scale: 1.0 },
	{ name: "Picture 20", src: "/logos/agile.webp", scale: 1.0 },
	{ name: "Picture 21", src: "/logos/picture21.webp", scale: 1.0 },
	{ name: "Picture 22", src: "/logos/picture22.webp", scale: 1.0 },
	{ name: "Picture 23", src: "/logos/zhenhua-oil.webp", scale: 1.0 },
	{ name: "Picture 24", src: "/logos/first-finance.webp", scale: 1.0 },
	{ name: "Picture 25", src: "/logos/fortinet.webp", scale: 1.0 },
	{ name: "Picture 26", src: "/logos/dari.webp", scale: 1.0 },
	{ name: "Picture 27", src: "/logos/ankido-it.webp", scale: 1.0 },
	{ name: "Picture 29", src: "/logos/picture29.webp", scale: 1.0 },
	{ name: "Picture 30", src: "/logos/btp-infrastrutture.webp", scale: 1.0 },
	{ name: "Picture 31", src: "/logos/arab-payment-service.webp", scale: 1.0 },
	{ name: "Picture 32", src: "/logos/baghdad-chamber-commerce.webp", scale: 1.0 },
	{ name: "Picture 33", src: "/logos/basrah-gas-company-2.webp", scale: 1.0 },
	{ name: "Picture 36", src: "/logos/shell.webp", scale: 1.0 },
	{ name: "Picture 38", src: "/logos/national-investment-commission.webp", scale: 1.0 },
	{ name: "Picture 39", src: "/logos/midland-oil-company.webp", scale: 1.0 },
	{ name: "Picture 40", src: "/logos/picture40.webp", scale: 1.0 },
	{ name: "Picture 41", src: "/logos/health-insurance-commission.webp", scale: 1.0 },
	{ name: "Picture 43", src: "/logos/mitsubishi.webp", scale: 1.0 },
	{ name: "Picture 44", src: "/logos/aramex.webp", scale: 1.0 },
	{ name: "Picture 46", src: "/logos/iraq-private-banks-league.webp", scale: 1.0 },
	{ name: "Picture 47", src: "/logos/baker-hughes.webp", scale: 1.0 },
];
