export const BRAND_LOGOS: { name: string; src: string; scale?: number }[] = [
	// --- Named logos ---
	{ name: "Al Basrah Mas", src: "/logos/Al Basrah Mas.png", scale: 1.5 },
	{ name: "Al Aliaa", src: "/logos/Al-aliaa LOGO_Main.png", scale: 1.2 },
	{ name: "Alshaba", src: "/logos/Alshaba.png", scale: 1.0 },
	{ name: "BGT", src: "/logos/BGT.png", scale: 1.0 },
	{ name: "BOC", src: "/logos/BOCLOGO1.png", scale: 1.0 },
	{ name: "Basrah Gas", src: "/logos/Basrah-Gas.webp", scale: 1.0 },
	{ name: "BoB", src: "/logos/BoB Logo-2.png", scale: 1.0 },
	{ name: "Daewoo", src: "/logos/Daewoo Engineering & Construction.png", scale: 1.0 },
	{ name: "Dev Road", src: "/logos/Dev Road Logo.png", scale: 1.0 },
	{ name: "Earthlink", src: "/logos/Earthlink_Telecommunications_Logo.png", scale: 1.0 },
	{ name: "Euler", src: "/logos/Euler.png", scale: 1.0 },
	{ name: "GFP", src: "/logos/GFP.png", scale: 1.0 },
	{ name: "ICC", src: "/logos/ICC.png", scale: 1.0 },
	{ name: "IDB", src: "/logos/IDB-Logo-Primary-Dual-RGB-e1675853108729.png", scale: 1.0 },
	{ name: "IFPMC", src: "/logos/IFPMC.png", scale: 1.0 },
	{ name: "Jwar Al Khaleej", src: "/logos/Jwar Al Khaleej.png", scale: 1.0 },
	{ name: "SOMO", src: "/logos/Logo_of_State_Organization_for_Marketing_of_Oil.png", scale: 1.0 },
	{ name: "Nokia", src: "/logos/Nokia.png", scale: 1.0 },
	{ name: "Oliver Wyman", src: "/logos/OliverWyman_rgb_c.png", scale: 1.0 },
	{ name: "Iraqi Ports", src: "/logos/Ports logo.png", scale: 1.0 },
	{ name: "SuperCell", src: "/logos/SuperCell.png", scale: 1.0 },
	{ name: "Technital", src: "/logos/Technital.png", scale: 1.0 },
	{ name: "Tiryaki Agro", src: "/logos/Tiryaki Agro.png", scale: 1.0 },
	{ name: "Visa", src: "/logos/Visa_Inc._logo.svg.png", scale: 1.0 },
	{ name: "Genesys", src: "/logos/genesys.png", scale: 1.0 },
	{ name: "Imathia", src: "/logos/imathia.png", scale: 1.0 },
	{ name: "JIB", src: "/logos/jib.png", scale: 1.0 },
	{ name: "Ministry of Transport", src: "/logos/شعار_وزارة_النقل_(1).png", scale: 1.0 },
	{ name: "Iraq Development Fund", src: "/logos/صندوق العراق للتنمية.png", scale: 1.0 },
	{ name: "Kul Al Manafeth", src: "/logos/كل المنافذ.png", scale: 1.0 },
	{ name: "Ministry of Oil", src: "/logos/وزارة_النفط_العراقية.svg.png", scale: 1.0 },

	// --- Additional logos from public/logos ---
	{ name: "2", src: "/logos/2.png", scale: 1.0 },
	{ name: "4", src: "/logos/4.png", scale: 1.0 },
	{ name: "4k logo", src: "/logos/4k logo.png", scale: 1.0 },
	{ name: "6", src: "/logos/6.png", scale: 1.0 },
	{ name: "9438 General Secretariat", src: "/logos/9438الامانة العامة.png", scale: 1.0 },
	{ name: "Technital CMYK", src: "/logos/Logo Technital - CMYK (10-11-21-19).png", scale: 1.0 },
	{ name: "Rida", src: "/logos/Rida-Logo-1-600x847-1.png", scale: 1.0 },
	{ name: "Ts", src: "/logos/Ts.png", scale: 1.0 },
	{ name: "Logo 2", src: "/logos/logo-2.png", scale: 1.0 },
	{ name: "NB Telecom", src: "/logos/nbtel-logo.png", scale: 1.0 },
	{ name: "Mufarrag x4", src: "/logos/مفرغ x4.png", scale: 1.0 },

	// --- Picture logos ---
	{ name: "Picture 7", src: "/logos/Picture7.png", scale: 1.0 },
	{ name: "Picture 9", src: "/logos/Picture9.png", scale: 1.0 },
	{ name: "Picture 12", src: "/logos/Picture12.png", scale: 1.0 },
	{ name: "Picture 17", src: "/logos/Picture17.png", scale: 1.0 },
	{ name: "Picture 18", src: "/logos/Picture18 (1).png", scale: 1.0 },
	{ name: "Picture 182", src: "/logos/Picture182.png", scale: 1.0 },
	{ name: "Picture 19", src: "/logos/Picture19.png", scale: 1.0 },
	{ name: "Picture 20", src: "/logos/Picture20.png", scale: 1.0 },
	{ name: "Picture 21", src: "/logos/Picture21.png", scale: 1.0 },
	{ name: "Picture 22", src: "/logos/Picture22.png", scale: 1.0 },
	{ name: "Picture 23", src: "/logos/Picture23.png", scale: 1.0 },
	{ name: "Picture 24", src: "/logos/Picture24.png", scale: 1.0 },
	{ name: "Picture 25", src: "/logos/Picture25.png", scale: 1.0 },
	{ name: "Picture 26", src: "/logos/Picture26.png", scale: 1.0 },
	{ name: "Picture 27", src: "/logos/Picture27.png", scale: 1.0 },
	{ name: "Picture 29", src: "/logos/Picture29.png", scale: 1.0 },
	{ name: "Picture 30", src: "/logos/Picture30.png", scale: 1.0 },
	{ name: "Picture 31", src: "/logos/Picture31.png", scale: 1.0 },
	{ name: "Picture 32", src: "/logos/Picture32.png", scale: 1.0 },
	{ name: "Picture 33", src: "/logos/Picture33.png", scale: 1.0 },
	{ name: "Picture 36", src: "/logos/Picture36.png", scale: 1.0 },
	{ name: "Picture 38", src: "/logos/Picture38.png", scale: 1.0 },
	{ name: "Picture 39", src: "/logos/Picture39.png", scale: 1.0 },
	{ name: "Picture 40", src: "/logos/Picture40.png", scale: 1.0 },
	{ name: "Picture 41", src: "/logos/Picture41.png", scale: 1.0 },
	{ name: "Picture 43", src: "/logos/Picture43.png", scale: 1.0 },
	{ name: "Picture 44", src: "/logos/Picture44.png", scale: 1.0 },
	{ name: "Picture 46", src: "/logos/Picture46.png", scale: 1.0 },
	{ name: "Picture 47", src: "/logos/Picture47.png", scale: 1.0 },
];
