/**
 * AUTO-GENERATED by scripts/generate-hero-slides.mjs — do not edit by hand.
 * To add a hero slide, drop an image into public/images/hero/ and restart the dev server.
 */
export const HERO_SLIDES: string[] = [
	"/images/hero/about-team.webp",
	"/images/hero/hero-summit.webp",
	"/images/hero/venture-iraq24.webp"
];
